// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2fhnRTtHAeMldDhVgvTIRAbs3iz-KO0',
    appId: '1:407536482549:web:60713934a36fdd7ba82dbc',
    messagingSenderId: '407536482549',
    projectId: 'pingo-955ac',
    authDomain: 'pingo-955ac.firebaseapp.com',
    storageBucket: 'pingo-955ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3H2sKNHWx27jZym60IYGEFI5IIqmHSk',
    appId: '1:407536482549:android:93024b669085fbc1a82dbc',
    messagingSenderId: '407536482549',
    projectId: 'pingo-955ac',
    storageBucket: 'pingo-955ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7PsaEhlMIKE0IxWnf5C_qihcRgFTFo8',
    appId: '1:407536482549:ios:b674abf592d9c59ea82dbc',
    messagingSenderId: '407536482549',
    projectId: 'pingo-955ac',
    storageBucket: 'pingo-955ac.appspot.com',
    iosBundleId: 'com.example.pingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7PsaEhlMIKE0IxWnf5C_qihcRgFTFo8',
    appId: '1:407536482549:ios:b674abf592d9c59ea82dbc',
    messagingSenderId: '407536482549',
    projectId: 'pingo-955ac',
    storageBucket: 'pingo-955ac.appspot.com',
    iosBundleId: 'com.example.pingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2fhnRTtHAeMldDhVgvTIRAbs3iz-KO0',
    appId: '1:407536482549:web:737943861c41c187a82dbc',
    messagingSenderId: '407536482549',
    projectId: 'pingo-955ac',
    authDomain: 'pingo-955ac.firebaseapp.com',
    storageBucket: 'pingo-955ac.appspot.com',
  );
}
